<a href="https://colab.research.google.com/github/ananthi25/Git_Practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#importing libraries
import numpy as np

In [6]:
#Printing Array using Numpy
demo=[10,20,30]
print(demo)
np.array(demo)

[10, 20, 30]


array([10, 20, 30])

In [9]:
#Converting all as string
#demo2=[10,20,"30"]
#np.array(demo2)
demo2=[10,20,"xyz"]
np.array(demo2)

array(['10', '20', 'xyz'], dtype='<U21')

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])