<a href="https://colab.research.google.com/github/ananthi25/Git_Practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Library**

In [8]:
#importing libraries
import numpy as np

**Printing array in numpy**

In [6]:
#Printing Array using Numpy
demo=[10,20,30]
print(demo)
np.array(demo)

[10, 20, 30]


array([10, 20, 30])

In [9]:
#Converting all as string
#demo2=[10,20,"30"]
#np.array(demo2)
demo2=[10,20,"xyz"]
np.array(demo2)

array(['10', '20', 'xyz'], dtype='<U21')

**Zeros And Ones**

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
x1=np.ones(5)
print(x1)

[1. 1. 1. 1. 1.]


In [16]:
x1[2]="xyz"

ValueError: ignored

In [21]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
x=np.zeros(10)
x.dtype

dtype('float64')

In [20]:
y=np.zeros(10,int)
y.dtype

dtype('int64')

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
x2=np.ones(5)
x2[3]=2
print(x2)

[1. 1. 1. 2. 1.]


**3D Array**

In [29]:
#3D array
new_array=np.zeros((3,4,5))
print(new_array)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [33]:
print(new_array[0][1][2])
print(new_array[0][1])
new_array[0]

0.0
[0. 0. 0. 0. 0.]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**Shape**

In [34]:
#Shape
new_array.shape

(3, 4, 5)

**Slicing**

In [37]:
#Slicing
a=np.zeros(5)
print(a)
a[2:5]

[0. 0. 0. 0. 0.]


array([0., 0., 0.])

**2D Array**

In [45]:
twoD_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD_array)

print("\n",twoD_array[2])
print("\n")
print(twoD_array[0:2])  #slicing
print("\n")
print(twoD_array[:,1])#all row index[1] element

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [7 8 9]


[[1 2 3]
 [4 5 6]]


[2 5 8]


In [54]:
new_twoD_array=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(new_twoD_array[:,1])
print(new_twoD_array[0:3,1]) #Slicing-1:3 as row,0-colum inside list
new_twoD_array[0:3,0:2]

[ 2  5  8 11]
[2 5 8]


array([[1, 2],
       [4, 5],
       [7, 8]])

## **Mathematial Operations between two numpy arrays**

In [55]:
import numpy as np
import math as m

In [56]:
x=[1,2,3]  
y=[3,5,6]
x=x+10      # Normal Array-It's Shows Error for this math

TypeError: ignored

In [59]:
x=np.array([1,2,3]) 
y=np.array([3,5,6])
x=x+10                   #In Numpy it can't show any error 
print(x)
print(x+y)

[11 12 13]
[14 17 19]


In [60]:
z=np.array([100,200,300,400]) 
print(y+z)#Error-y has 3 elements,z has 4 elements

ValueError: ignored

In [62]:
print(x*2)
print(x*y)
print(x**3)

[22 24 26]
[33 60 78]
[1331 1728 2197]


In [65]:
print(x.mean())
print(x.sum())

12.0
36


In [70]:
p1=np.array([2,2,2])   #Find Distance ((x2-x1)**2+(y2-y1)**2)**2
p2=np.array([1,1,1])

val=((p1-p2)**2).sum()
print(val)

#val2=val.sum()
#print(val2)

m.sqrt(val)

3


1.7320508075688772

In [71]:
m1=np.array([1,2,3])
m2=np.array([4,5,6])
print(m1.dot(m2))

32


### **Inspecting Properties**

*   arr.size
*   arr.shape
*   arr.dtype
*   arr.astype(dtype)
*   arr.tolist()

### **Copying/Sorting/Reshaping **
* np.copy(arr)
* arr.view(dtype)
* arr.sort()

### **Adding/Removing Elements**
* np.append(arr,values)
* np.insert(arr,2,values)
* np.delete(arr,3,axis=0)
* np.delete(arr,4,axis=1)
 
### **Scalar Math**
* np.add(arr,1)
* np.subtract(arr,2)
* np.multiply(arr,3)
* np.divide(arr,4)
* np.power(arr,5)

### **Vector Math**
* np.add(arr1,arr2)
* np.subtract(arr1,arr2)
* np.multiply(arr1,arr2)
* np.divide(arr1,arr2)
* np.power(arr1,arr2)
* np.array_equal(arr1,arr2)
* np.sqrt(arr)
* np.sin(arr)
* np.log(arr)
* np.abs(arr)
* np.ceil(arr)
* np.floor(arr)
* np.round(arr)

### **Statistics**
* np.mean(arr,axis=0)
* arr.sum()
* arr.min()
* arr.max(axis=0)
* np.var(arr)
* np.std(arr,axis=1)
* arr.corrcoef()


For More
https://numpy.org/doc/stable/

