<a href="https://colab.research.google.com/github/ananthi25/Git_Practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#importing libraries
import numpy as np

In [6]:
#Printing Array using Numpy
demo=[10,20,30]
print(demo)
np.array(demo)

[10, 20, 30]


array([10, 20, 30])

In [9]:
#Converting all as string
#demo2=[10,20,"30"]
#np.array(demo2)
demo2=[10,20,"xyz"]
np.array(demo2)

array(['10', '20', 'xyz'], dtype='<U21')

**Zeros And Ones**

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
x1=np.ones(5)
print(x1)

[1. 1. 1. 1. 1.]


In [16]:
x1[2]="xyz"

ValueError: ignored

In [21]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
x=np.zeros(10)
x.dtype

dtype('float64')

In [20]:
y=np.zeros(10,int)
y.dtype

dtype('int64')

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
x2=np.ones(5)
x2[3]=2
print(x2)

[1. 1. 1. 2. 1.]


**3D Array**

In [29]:
#3D array
new_array=np.zeros((3,4,5))
print(new_array)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [33]:
print(new_array[0][1][2])
print(new_array[0][1])
new_array[0]

0.0
[0. 0. 0. 0. 0.]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**Shape**

In [34]:
#Shape
new_array.shape

(3, 4, 5)

**Slicing**

In [37]:
#Slicing
a=np.zeros(5)
print(a)
a[2:5]

[0. 0. 0. 0. 0.]


array([0., 0., 0.])